swagger: "2.0"
info:
  description: This is a service API
  version: 0.0.1
  title: service API
  contact:
    email: info@kuberlogic.com

tags:
  - name: service
    description: Everything about service resource

host: localhost:8001
basePath: /api/v1/
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: x-token
security:
  - key: [ ]
paths:
  /backups/:
    get:
      tags:
        - backup
      summary: list backups
      description: List backup objects
      operationId: backupList
      parameters:
        - $ref: "#/parameters/BackupRestoreServiceID"
      responses:
        200:
          description: search results matching criteria
          schema:
            $ref: "#/definitions/Backups"
        400:
          description: bad input parameter
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        403:
          description: bad permissions
        422:
          description: bad validation
          schema:
            $ref: "#/definitions/Error"
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - backup
      summary: create backup object
      description: Create backup object
      operationId: backupAdd
      parameters:
        - $ref: "#/parameters/BackupItem"
      responses:
        201:
          description: item created
          schema:
            $ref: "#/definitions/Backup"
        400:
          description: invalid input, object invalid
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        409:
          description: item already exists
        422:
          description: bad validation
          schema:
            $ref: "#/definitions/Error"
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"
  /backups/{BackupID}/:
    delete:
      tags:
        - backup
      summary: deletes a backup item
      operationId: backupDelete
      description: |
        Deletes a backup object
      parameters:
        - $ref: "#/parameters/BackupID"

      responses:
        200:
          description: item deleted
        400:
          description: invalid input, object invalid
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        403:
          description: bad permissions
        404:
          description: item not found
          schema:
            $ref: "#/definitions/Error"
        422:
          description: bad validation
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"

  /restores/:
    get:
      tags:
        - restore
      summary: list restores
      description: List restore objects
      operationId: restoreList
      parameters:
        - $ref: "#/parameters/BackupRestoreServiceID"
      responses:
        200:
          description: search results matching criteria
          schema:
            $ref: "#/definitions/Restores"
        400:
          description: bad input parameter
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        403:
          description: bad permissions
        422:
          description: bad validation
          schema:
            $ref: "#/definitions/Error"
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - restore
      summary: create restore object
      description: Create restore object
      operationId: restoreAdd
      parameters:
        - $ref: "#/parameters/RestoreItem"
      responses:
        201:
          description: item created
          schema:
            $ref: "#/definitions/Restore"
        400:
          description: invalid input, object invalid
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        409:
          description: item already exists
        422:
          description: bad validation
          schema:
            $ref: "#/definitions/Error"
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"
  /restores/{RestoreID}/:
    delete:
      tags:
        - restore
      summary: deletes a restore item
      operationId: restoreDelete
      description: |
        Deletes a restore object
      parameters:
        - $ref: "#/parameters/RestoreID"

      responses:
        200:
          description: item deleted
        400:
          description: invalid input, object invalid
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        403:
          description: bad permissions
        404:
          description: item not found
          schema:
            $ref: "#/definitions/Error"
        422:
          description: bad validation
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"

  /services/:
    get:
      tags:
        - service
      summary: lists all services
      operationId: serviceList
      description: |
        List of service objects
      parameters:
        - $ref: "#/parameters/SubscriptionID"
      responses:
        200:
          description: search results matching criteria
          schema:
            $ref: "#/definitions/Services"
        400:
          description: bad input parameter
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        403:
          description: bad permissions
        422:
          description: bad validation
          schema:
            $ref: "#/definitions/Error"
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - service
      summary: adds a service item
      operationId: serviceAdd
      description: |
        Adds service object
      parameters:
        - $ref: "#/parameters/ServiceItem"
      responses:
        201:
          description: item created
          schema:
            $ref: "#/definitions/Service"
        400:
          description: invalid input, object invalid
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        403:
          description: bad permissions
        409:
          description: item already exists
        422:
          description: bad validation
          schema:
            $ref: "#/definitions/Error"
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"
  /services/{ServiceID}/:
    get:
      tags:
        - service
      summary: get a service item
      operationId: serviceGet
      description: |
        Get service object
      parameters:
        - $ref: "#/parameters/ServiceID"
      responses:
        200:
          description: item edited
          schema:
            $ref: "#/definitions/Service"
        400:
          description: invalid input, object invalid
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        403:
          description: bad permissions
        404:
          description: item not found
          schema:
            $ref: "#/definitions/Error"
        422:
          description: bad validation
          schema:
            $ref: "#/definitions/Error"
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"

    patch:
      tags:
        - service
      summary: edit a service item
      operationId: serviceEdit
      description: |
        Edit service object
      parameters:
        - $ref: "#/parameters/ServiceID"
        - $ref: "#/parameters/ServiceItem"
      responses:
        200:
          description: item edited
          schema:
            $ref: "#/definitions/Service"
        400:
          description: invalid input, object invalid
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        403:
          description: bad permissions
        404:
          description: item not found
          schema:
            $ref: "#/definitions/Error"
        422:
          description: bad validation
          schema:
            $ref: "#/definitions/Error"
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
        - service
      summary: deletes a service item
      operationId: serviceDelete
      description: |
        Deletes a service object
      parameters:
        - $ref: "#/parameters/ServiceID"

      responses:
        200:
          description: item deleted
        400:
          description: invalid input, object invalid
          schema:
            $ref: "#/definitions/Error"
        401:
          description: bad authentication
        403:
          description: bad permissions
        404:
          description: item not found
          schema:
            $ref: "#/definitions/Error"
        422:
          description: bad validation
        503:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"

definitions:
  Advanced:
    type: object
    additionalProperties:
      type: object

  Limits:
    type: object
    properties:
      cpu:
        type: string
      memory:
        type: string
      volumeSize:
        type: string

  Service:
    type: object
    required:
      - id
      - type
    properties:
      id:
        type: string
        pattern: "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
        minLength: 2
        maxLength: 20
      type:
        type: string
      version:
        type: string
      tlsEnabled:
        type: boolean
      domain:
        type: string
      replicas:
        # https://goswagger.io/faq/faq_model.html#non-required-or-nullable-property
        x-nullable: true
        type: integer
      backupSchedule:
        type: string
      limits:
        $ref: "#/definitions/Limits"
      advanced:
        $ref: "#/definitions/Advanced"
      status:
        type: string
        readOnly: true

      created_at:
        type: string
        readOnly: true
        format: date-time

      endpoint:
        type: string
        readOnly: true

      subscription:
        type: string

  Services:
    type: array
    items:
      $ref: "#/definitions/Service"

  Backups:
    type: array
    items:
      $ref: "#/definitions/Backup"

  Backup:
    type: object
    properties:
      id:
        type: string
        pattern: "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
        minLength: 2
        maxLength: 63
        readOnly: true
      service_id:
        type: string
        pattern: "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
        minLength: 2
        maxLength: 20
      created_at:
        type: string
        readOnly: true
        format: date-time
      status:
        type: string

  Restore:
    type: object
    properties:
      id:
        type: string
        pattern: "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
        minLength: 2
        maxLength: 63
        readOnly: true
      backup_id:
        type: string
        pattern: "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
        minLength: 2
        maxLength: 63
      created_at:
        type: string
        readOnly: true
        format: date-time
      status:
        type: string

  Restores:
    type: array
    items:
      $ref: "#/definitions/Restore"

  Error:
    type: object
    properties:
      message:
        type: string

  principal:
    type: string

parameters:
  ServiceID:
    name: ServiceID
    in: path
    description: service Resource ID
    required: true
    type: "string"
    pattern: "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
    minLength: 3
    maxLength: 20

  ServiceItem:
    in: body
    name: serviceItem
    required: true
    description: service item
    schema:
      $ref: "#/definitions/Service"

  BackupID:
    name: BackupID
    in: path
    description: backup Resource ID
    required: true
    type: "string"
    pattern: "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
    minLength: 3
    maxLength: 63

  RestoreItem:
    in: body
    name: restoreItem
    required: true
    description: restore item
    schema:
      $ref: "#/definitions/Restore"

  RestoreID:
    name: RestoreID
    in: path
    description: restore Resource ID
    required: true
    type: "string"
    pattern: "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
    minLength: 3
    maxLength: 63

  BackupItem:
    in: body
    name: backupItem
    required: true
    description: backup item
    schema:
      $ref: "#/definitions/Backup"

  BackupRestoreServiceID:
    name: ServiceID
    in: query
    description: service Resource ID to query backups/restores by
    type: "string"
    pattern: "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
    minLength: 3
    maxLength: 20

  SubscriptionID:
    name: SubscriptionID
    in: query
    description: subscription ID
    required: false
    type: "string"
