codecov:
  bot: "codecov-io"

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    patch:
      default:
        threshold: 50%
        flags:
          - apiserver
          - operator
          - unit-operator
          - unit-installer
          - unit-apiserver
    project:
      threshold: 1%
      default:
        flags:
          - apiserver
          - operator
          - unit-operator
          - unit-installer
          - unit-apiserver

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no