// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Defaults) DeepCopyInto(out *Defaults) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Defaults.
func (in *Defaults) DeepCopy() *Defaults {
	if in == nil {
		return nil
	}
	out := new(Defaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (kls *KuberLogicService) DeepCopyInto(out *KuberLogicService) {
	*out = *kls
	out.TypeMeta = kls.TypeMeta
	kls.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	kls.Spec.DeepCopyInto(&out.Spec)
	out.Status = kls.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicService.
func (kls *KuberLogicService) DeepCopy() *KuberLogicService {
	if kls == nil {
		return nil
	}
	out := new(KuberLogicService)
	kls.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (kls *KuberLogicService) DeepCopyObject() runtime.Object {
	if c := kls.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicAlert) DeepCopyInto(out *KuberLogicAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicAlert.
func (in *KuberLogicAlert) DeepCopy() *KuberLogicAlert {
	if in == nil {
		return nil
	}
	out := new(KuberLogicAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicAlertList) DeepCopyInto(out *KuberLogicAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KuberLogicAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicAlertList.
func (in *KuberLogicAlertList) DeepCopy() *KuberLogicAlertList {
	if in == nil {
		return nil
	}
	out := new(KuberLogicAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicAlertSpec) DeepCopyInto(out *KuberLogicAlertSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicAlertSpec.
func (in *KuberLogicAlertSpec) DeepCopy() *KuberLogicAlertSpec {
	if in == nil {
		return nil
	}
	out := new(KuberLogicAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicAlertStatus) DeepCopyInto(out *KuberLogicAlertStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicAlertStatus.
func (in *KuberLogicAlertStatus) DeepCopy() *KuberLogicAlertStatus {
	if in == nil {
		return nil
	}
	out := new(KuberLogicAlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicBackupRestore) DeepCopyInto(out *KuberLogicBackupRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicBackupRestore.
func (in *KuberLogicBackupRestore) DeepCopy() *KuberLogicBackupRestore {
	if in == nil {
		return nil
	}
	out := new(KuberLogicBackupRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicBackupRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicBackupRestoreList) DeepCopyInto(out *KuberLogicBackupRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KuberLogicBackupRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicBackupRestoreList.
func (in *KuberLogicBackupRestoreList) DeepCopy() *KuberLogicBackupRestoreList {
	if in == nil {
		return nil
	}
	out := new(KuberLogicBackupRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicBackupRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicBackupRestoreSpec) DeepCopyInto(out *KuberLogicBackupRestoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicBackupRestoreSpec.
func (in *KuberLogicBackupRestoreSpec) DeepCopy() *KuberLogicBackupRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(KuberLogicBackupRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicBackupRestoreStatus) DeepCopyInto(out *KuberLogicBackupRestoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicBackupRestoreStatus.
func (in *KuberLogicBackupRestoreStatus) DeepCopy() *KuberLogicBackupRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(KuberLogicBackupRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicBackupSchedule) DeepCopyInto(out *KuberLogicBackupSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicBackupSchedule.
func (in *KuberLogicBackupSchedule) DeepCopy() *KuberLogicBackupSchedule {
	if in == nil {
		return nil
	}
	out := new(KuberLogicBackupSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicBackupSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicBackupScheduleList) DeepCopyInto(out *KuberLogicBackupScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KuberLogicBackupSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicBackupScheduleList.
func (in *KuberLogicBackupScheduleList) DeepCopy() *KuberLogicBackupScheduleList {
	if in == nil {
		return nil
	}
	out := new(KuberLogicBackupScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicBackupScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicBackupScheduleSpec) DeepCopyInto(out *KuberLogicBackupScheduleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicBackupScheduleSpec.
func (in *KuberLogicBackupScheduleSpec) DeepCopy() *KuberLogicBackupScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(KuberLogicBackupScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicBackupScheduleStatus) DeepCopyInto(out *KuberLogicBackupScheduleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicBackupScheduleStatus.
func (in *KuberLogicBackupScheduleStatus) DeepCopy() *KuberLogicBackupScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(KuberLogicBackupScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicServiceList) DeepCopyInto(out *KuberLogicServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KuberLogicService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicServiceList.
func (in *KuberLogicServiceList) DeepCopy() *KuberLogicServiceList {
	if in == nil {
		return nil
	}
	out := new(KuberLogicServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicServiceSpec) DeepCopyInto(out *KuberLogicServiceSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.AdvancedConf != nil {
		in, out := &in.AdvancedConf, &out.AdvancedConf
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.MaintenanceWindow = in.MaintenanceWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicServiceSpec.
func (in *KuberLogicServiceSpec) DeepCopy() *KuberLogicServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KuberLogicServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicServiceStatus) DeepCopyInto(out *KuberLogicServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicServiceStatus.
func (in *KuberLogicServiceStatus) DeepCopy() *KuberLogicServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KuberLogicServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}
