---
version: '3'
x-kuberlogic-secrets:
  secret-key: "{{ GenerateKey 30 }}"

services:
  planka:
    x-kuberlogic-set-credentials-cmd: "echo {{ .token }}"
    x-kuberlogic-health-endpoint: "/"
    image: ghcr.io/plankanban/planka:{{ or .Version "latest" }}
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - "3000:1337"
    environment:
      - BASE_URL={{ Endpoint "localhost:3000" }}
      - TRUST_PROXY=0
      - DATABASE_URL=postgresql://postgres@localhost/planka
      - SECRET_KEY={{ Secret "secret-key" }}
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
