apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      volumes:
        - name: manager-config
          configMap:
            name: manager-config
        - name: compose-file
          configMap:
            name: compose-file
      containers:
        - command:
            - /manager
          volumeMounts:
            - name: compose-file
              mountPath: /etc/compose-file
            - name: manager-config
              mountPath: /etc/manager-config
          env:
            - name: SVC_OPTS_TLS_SECRET_NAME
              value: $(TLS_SECRET_NAME)
            - name: PLUGINS
              value: "{docker-compose,/docker-compose-plugin}"
            - name: KL_PLUGIN_DOCKER_COMPOSE_FILE
              value: "/etc/compose-file/docker-compose.yaml"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_ACCOUNT
              value: $(SERVICE_ACCOUNT)
            - name: INGRESS_CLASS
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: INGRESS_CLASS
            - name: STORAGE_CLASS
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: STORAGE_CLASS
            - name: BACKUPS_ENABLED
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: BACKUPS_ENABLED
            - name: BACKUPS_SNAPSHOTS_ENABLED
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: BACKUPS_SNAPSHOTS_ENABLED
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: SENTRY_DSN
          args:
            - --manager-config=/etc/manager-config/controller_manager_config.yaml
          image: controller:latest
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
        - command:
            - /cmd
          args:
            - --scheme=http
          image: apiserver:latest
          name: apiserver
          env:
            - name: KUBERLOGIC_APISERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: TOKEN
            - name: KUBERLOGIC_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: SENTRY_DSN
          ports:
            - containerPort: 8001
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
        - command:
            - /cmd
          image: chargebee-integration:latest
          name: chargebee-integration
          env:
            - name: KUBERLOGIC_APISERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: TOKEN
            - name: KUBERLOGIC_APISERVER_SCHEME
              value: http
            - name: KUBERLOGIC_APISERVER_HOST
              value: localhost:8001
            - name: CHARGEBEE_SITE
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: CHARGEBEE_SITE
            - name: CHARGEBEE_KEY
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: CHARGEBEE_KEY
            - name: KUBERLOGIC_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: KUBERLOGIC_DOMAIN
            - name: KUBERLOGIC_TYPE
              value: docker-compose
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: kuberlogic-config
                  key: SENTRY_DSN
          ports:
            - containerPort: 4242
          resources:
            limits:
              cpu: 50m
              memory: 30Mi
            requests:
              cpu: 50m
              memory: 20Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
