---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: namespace
spec:
  ports:
    - name: http
      nodePort: 30007
      port: 80
      protocol: TCP
      targetPort: 8001
  selector:
    control-plane: controller-manager
  type: LoadBalancer