resources:
- certificate.yaml

configurations:
- kustomizeconfig.yaml

secretGenerator:
  - name: tls-secret
    files:
      - tls.key
      - tls.crt

configMapGenerator:
- env: config.env
  name: runtime-secrets

vars:
- name: ADMIN_EMAIL
  objref:
    kind: ConfigMap
    name: runtime-secrets
    apiVersion: v1
  fieldref:
    fieldpath: data.ADMIN_EMAIL
- name: INGRESS_CLASS
  objref:
    kind: ConfigMap
    name: runtime-secrets
    apiVersion: v1
  fieldref:
    fieldpath: data.INGRESS_CLASS
