package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"github.com/go-openapi/runtime"
	"github.com/kuberlogic/kuberlogic/modules/dynamic-apiserver/internal/generated/client"
	"github.com/kuberlogic/kuberlogic/modules/dynamic-apiserver/internal/generated/client/service"
	util2 "github.com/kuberlogic/kuberlogic/modules/dynamic-apiserver/internal/util"
	"github.com/pkg/errors"

	"github.com/spf13/cobra"
)

// makeServiceDeleteCmd returns a cmd to handle operation serviceDelete
func makeServiceDeleteCmd(apiClient *client.ServiceAPI) (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:     "serviceDelete",
		Short:   `Deletes a service object`,
		Aliases: []string{"delete"},
		RunE:    runServiceDelete(apiClient),
	}

	_ = cmd.PersistentFlags().String("name", "", "name of service")
	_ = cmd.PersistentFlags().String("namespace", "", "namespace of service")

	return cmd, nil
}

// runServiceDelete uses cmd flags to call endpoint api
func runServiceDelete(apiClient *client.ServiceAPI) func(cmd *cobra.Command, args []string) error {
	return func(cmd *cobra.Command, args []string) error {

		// retrieve flag values from cmd and fill params
		params := service.NewServiceDeleteParams()

		var name, namespace string
		if value, err := getString(cmd, "name"); err != nil {
			return err
		} else if value != nil {
			name = *value
		}

		if value, err := getString(cmd, "namespace"); err != nil {
			return err
		} else if value != nil {
			namespace = *value
		}

		serviceId, err := util2.JoinID(namespace, name)
		if err != nil {
			return err
		}
		params.ServiceID = serviceId

		var formatResponse format
		if value, err := getString(cmd, "format"); err != nil {
			return err
		} else if value != nil {
			formatResponse = format(*value)
		}

		if dryRun {
			logDebugf("dry-run flag specified. Skip sending request.")
			return nil
		}

		payload, e := apiClient.Service.ServiceDelete(params)
		// make request and then print result
		err = parseServiceDeleteResult(name, namespace, e)
		if err != nil {
			return err
		}
		if isDefaultPrintFormat(formatResponse) {
			_, err := fmt.Fprintf(cmd.OutOrStdout(), "Service '%s' successfully removed\n", name)
			return err
		} else {
			return printResult(cmd, formatResponse, payload)
		}
	}
}

// parseServiceListResult parses request result and return the string content
func parseServiceDeleteResult(name, namespace string, respErr error) error {
	if respErr != nil {
		switch respErr.(type) {
		case *service.ServiceDeleteBadRequest:
			err := respErr.(*service.ServiceDeleteBadRequest)
			return errors.Errorf(err.Payload.Message)
		case *service.ServiceDeleteServiceUnavailable:
			return errors.Errorf("Service unavailable [%v]", respErr)
		case *service.ServiceDeleteUnauthorized:
			return errors.Errorf("Unauthorized [%v]", respErr)
		case *service.ServiceDeleteForbidden:
			return errors.Errorf("Forbidden [%v]", respErr)
		case *service.ServiceDeleteNotFound:
			return errors.Errorf("Record not found with name '%s' and namespace '%s'", name, namespace)
		case *service.ServiceDeleteUnprocessableEntity:
			//err := respErr.(*service.ServiceDeleteUnprocessableEntity)
			return errors.Errorf("validation error: %s", "")
		case *runtime.APIError:
			return errors.Errorf("APIError [%v]", respErr)
		default:
			return errors.Errorf("Unknown response type: %T [%v]", respErr, respErr)
		}
	}
	return nil
}
