// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Schema cli for []*Service

// Name: [Services], Type:[[]*Service], register and retrieve functions are not rendered by go-swagger cli
