// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/kuberlogic/kuberlogic/modules/dynamic-apiserver/internal/generated/client/service"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationServiceServiceDeleteCmd returns a cmd to handle operation serviceDelete
func makeOperationServiceServiceDeleteCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "serviceDelete",
		Short: `Deletes a service object
`,
		RunE: runOperationServiceServiceDelete,
	}

	if err := registerOperationServiceServiceDeleteParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationServiceServiceDelete uses cmd flags to call endpoint api
func runOperationServiceServiceDelete(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := service.NewServiceDeleteParams()
	if err, _ := retrieveOperationServiceServiceDeleteServiceIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationServiceServiceDeleteResult(appCli.Service.ServiceDelete(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationServiceServiceDeleteParamFlags registers all flags needed to fill params
func registerOperationServiceServiceDeleteParamFlags(cmd *cobra.Command) error {
	if err := registerOperationServiceServiceDeleteServiceIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationServiceServiceDeleteServiceIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	serviceIdDescription := `Required. service Resource ID`

	var serviceIdFlagName string
	if cmdPrefix == "" {
		serviceIdFlagName = "ServiceID"
	} else {
		serviceIdFlagName = fmt.Sprintf("%v.ServiceID", cmdPrefix)
	}

	var serviceIdFlagDefault string

	_ = cmd.PersistentFlags().String(serviceIdFlagName, serviceIdFlagDefault, serviceIdDescription)

	return nil
}

func retrieveOperationServiceServiceDeleteServiceIDFlag(m *service.ServiceDeleteParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("ServiceID") {

		var serviceIdFlagName string
		if cmdPrefix == "" {
			serviceIdFlagName = "ServiceID"
		} else {
			serviceIdFlagName = fmt.Sprintf("%v.ServiceID", cmdPrefix)
		}

		serviceIdFlagValue, err := cmd.Flags().GetString(serviceIdFlagName)
		if err != nil {
			return err, false
		}
		m.ServiceID = serviceIdFlagValue

	}
	return nil, retAdded
}

// parseOperationServiceServiceDeleteResult parses request result and return the string content
func parseOperationServiceServiceDeleteResult(resp0 *service.ServiceDeleteOK, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning serviceDeleteOK is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*service.ServiceDeleteBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning serviceDeleteUnauthorized is not supported

		// Non schema case: warning serviceDeleteForbidden is not supported

		// Non schema case: warning serviceDeleteNotFound is not supported

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*service.ServiceDeleteServiceUnavailable)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response serviceDeleteOK is not supported by go-swagger cli yet.

	return "", nil
}
