apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updater
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: updater
              env:
                - name: REGISTRY_API
                  value: https://quay.io/v2/