//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * CloudLinux Software Inc 2019-2021 All Rights Reserved
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicService) DeepCopyInto(out *KuberLogicService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicService.
func (in *KuberLogicService) DeepCopy() *KuberLogicService {
	if in == nil {
		return nil
	}
	out := new(KuberLogicService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicServiceList) DeepCopyInto(out *KuberLogicServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KuberLogicService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicServiceList.
func (in *KuberLogicServiceList) DeepCopy() *KuberLogicServiceList {
	if in == nil {
		return nil
	}
	out := new(KuberLogicServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicServiceSpec) DeepCopyInto(out *KuberLogicServiceSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.Advanced.DeepCopyInto(&out.Advanced)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicServiceSpec.
func (in *KuberLogicServiceSpec) DeepCopy() *KuberLogicServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KuberLogicServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicServiceStatus) DeepCopyInto(out *KuberLogicServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicServiceStatus.
func (in *KuberLogicServiceStatus) DeepCopy() *KuberLogicServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KuberLogicServiceStatus)
	in.DeepCopyInto(out)
	return out
}
