//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * CloudLinux Software Inc 2019-2021 All Rights Reserved
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicService) DeepCopyInto(out *KuberLogicService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicService.
func (in *KuberLogicService) DeepCopy() *KuberLogicService {
	if in == nil {
		return nil
	}
	out := new(KuberLogicService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicServiceList) DeepCopyInto(out *KuberLogicServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KuberLogicService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicServiceList.
func (in *KuberLogicServiceList) DeepCopy() *KuberLogicServiceList {
	if in == nil {
		return nil
	}
	out := new(KuberLogicServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberLogicServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicServiceSpec) DeepCopyInto(out *KuberLogicServiceSpec) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	in.Advanced.DeepCopyInto(&out.Advanced)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicServiceSpec.
func (in *KuberLogicServiceSpec) DeepCopy() *KuberLogicServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KuberLogicServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberLogicServiceStatus) DeepCopyInto(out *KuberLogicServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberLogicServiceStatus.
func (in *KuberLogicServiceStatus) DeepCopy() *KuberLogicServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KuberLogicServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberlogicServiceBackup) DeepCopyInto(out *KuberlogicServiceBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberlogicServiceBackup.
func (in *KuberlogicServiceBackup) DeepCopy() *KuberlogicServiceBackup {
	if in == nil {
		return nil
	}
	out := new(KuberlogicServiceBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberlogicServiceBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberlogicServiceBackupList) DeepCopyInto(out *KuberlogicServiceBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KuberlogicServiceBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberlogicServiceBackupList.
func (in *KuberlogicServiceBackupList) DeepCopy() *KuberlogicServiceBackupList {
	if in == nil {
		return nil
	}
	out := new(KuberlogicServiceBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberlogicServiceBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberlogicServiceBackupSpec) DeepCopyInto(out *KuberlogicServiceBackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberlogicServiceBackupSpec.
func (in *KuberlogicServiceBackupSpec) DeepCopy() *KuberlogicServiceBackupSpec {
	if in == nil {
		return nil
	}
	out := new(KuberlogicServiceBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberlogicServiceBackupStatus) DeepCopyInto(out *KuberlogicServiceBackupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberlogicServiceBackupStatus.
func (in *KuberlogicServiceBackupStatus) DeepCopy() *KuberlogicServiceBackupStatus {
	if in == nil {
		return nil
	}
	out := new(KuberlogicServiceBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberlogicServiceRestore) DeepCopyInto(out *KuberlogicServiceRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberlogicServiceRestore.
func (in *KuberlogicServiceRestore) DeepCopy() *KuberlogicServiceRestore {
	if in == nil {
		return nil
	}
	out := new(KuberlogicServiceRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberlogicServiceRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberlogicServiceRestoreList) DeepCopyInto(out *KuberlogicServiceRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KuberlogicServiceRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberlogicServiceRestoreList.
func (in *KuberlogicServiceRestoreList) DeepCopy() *KuberlogicServiceRestoreList {
	if in == nil {
		return nil
	}
	out := new(KuberlogicServiceRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KuberlogicServiceRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberlogicServiceRestoreSpec) DeepCopyInto(out *KuberlogicServiceRestoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberlogicServiceRestoreSpec.
func (in *KuberlogicServiceRestoreSpec) DeepCopy() *KuberlogicServiceRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(KuberlogicServiceRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KuberlogicServiceRestoreStatus) DeepCopyInto(out *KuberlogicServiceRestoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KuberlogicServiceRestoreStatus.
func (in *KuberlogicServiceRestoreStatus) DeepCopy() *KuberlogicServiceRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(KuberlogicServiceRestoreStatus)
	in.DeepCopyInto(out)
	return out
}
