# permissions for end users to edit kuberlogicservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberlogicservice-editor-role
rules:
- apiGroups:
  - kuberlogic.com
  resources:
  - kuberlogicservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberlogic.com
  resources:
  - kuberlogicservices/status
  verbs:
  - get
