# permissions for end users to edit kuberlogicservicetypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberlogicservicetype-editor-role
rules:
- apiGroups:
  - kuberlogic.com
  resources:
  - kuberlogicservicetypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberlogic.com
  resources:
  - kuberlogicservicetypes/status
  verbs:
  - get
