---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range tuple "handler.lua" "schema.lua" "JSON.lua" }}
    {{ . }}: |-
    {{ printf "%s/%s" "keycloak-token-introspect" . | $.Files.Get | nindent 6 }}
  {{- end }}