---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ .Values.kong.tokenIntrospectPlugin.name }}
  namespace: {{ .Release.Namespace }}
config:
  query_arg: {{ .Values.kong.tokenIntrospectPlugin.config.tokenArg }}
  introspection_url: {{ .Values.kong.tokenIntrospectPlugin.config.introspectionUrl }}
  basic_username: {{ .Values.kong.tokenIntrospectPlugin.config.basicUsername }}
  basic_password: {{ .Values.kong.tokenIntrospectPlugin.config.basicPassword }}
  id_claim: {{ .Values.kong.tokenIntrospectPlugin.config.idClaim }}
plugin: keycloak-token-introspect